import type {
  AuditReport,
  AuditStressTestCase,
  AuditTestFramework,
  GeneratedAuditTestFile,
  GenerateAuditTestOptions,
} from "./types";

export function generateAuditTestFiles(
  report: AuditReport,
  options: GenerateAuditTestOptions,
): GeneratedAuditTestFile[] {
  const framework = options.framework;
  const programName = normalizeProgramName(options.programName ?? "solstudio_program");
  const files: GeneratedAuditTestFile[] = [];

  if (framework === "anchor") {
    files.push({
      path: "tests/solstudio.audit.generated.ts",
      content: renderAnchorTests(report.stressTests, programName),
      language: "typescript",
      framework,
      testCount: report.stressTests.length,
    });
  } else if (framework === "pinocchio" || framework === "quasar") {
    files.push({
      path: "tests/solstudio_audit_generated.rs",
      content: renderRustTests(report.stressTests, framework),
      language: "rust",
      framework,
      testCount: report.stressTests.length,
    });
  } else if (framework === "litesvm") {
    files.push({
      path: "tests/solstudio_litesvm_generated.rs",
      content: renderLiteSvmHarness(report.stressTests),
      language: "rust",
      framework,
      testCount: report.stressTests.length,
    });
  } else {
    files.push({
      path: "tests/solstudio_mollusk_generated.rs",
      content: renderMolluskHarness(report.stressTests),
      language: "rust",
      framework,
      testCount: report.stressTests.length,
    });
  }

  files.push({
    path: "tests/solstudio.audit.cases.json",
    content: `${JSON.stringify(report.stressTests, null, 2)}\n`,
    language: "json",
    framework,
    testCount: report.stressTests.length,
  });

  if (options.includeReadme) {
    files.push({
      path: "tests/solstudio.audit.README.md",
      content: renderReadme(framework, files, report),
      language: "markdown",
      framework,
      testCount: report.stressTests.length,
    });
  }

  return files;
}

function renderAnchorTests(
  stressTests: AuditStressTestCase[],
  programName: string,
): string {
  return `import assert from "node:assert/strict";
import * as anchor from "@coral-xyz/anchor";

const stressCases = ${JSON.stringify(stressTests, null, 2)} as const;

describe("solstudio deterministic audit stress", () => {
  anchor.setProvider(anchor.AnchorProvider.env());

  it("loads the generated stress plan", () => {
    assert.ok(stressCases.length >= 0);
    assert.equal("${programName}".length > 0, true);
  });

  for (const testCase of stressCases) {
    it(\`\${testCase.instructionName}: \${testCase.title}\`, async () => {
      assert.ok(testCase.id);
      assert.ok(testCase.instructionName);
      assert.ok(["pass", "fail", "reject", "no-panic"].includes(testCase.expected));
      assert.ok(testCase.rationale.length > 0);
    });
  }
});
`;
}

function renderRustTests(
  stressTests: AuditStressTestCase[],
  framework: "pinocchio" | "quasar",
): string {
  const caseTests = stressTests
    .map((testCase, index) => {
      const name = rustIdent(`solstudio_${index}_${testCase.instructionName}_${testCase.category}`);
      return `#[test]
fn ${name}() {
    let case_id = ${JSON.stringify(testCase.id)};
    let instruction = ${JSON.stringify(testCase.instructionName)};
    let expected = ${JSON.stringify(testCase.expected)};
    assert!(!case_id.is_empty());
    assert!(!instruction.is_empty());
    assert!(matches!(expected, "pass" | "fail" | "reject" | "no-panic"));
}`;
    })
    .join("\n\n");

  return `// Generated by SolStudio audit for ${framework}.
// These tests encode the deterministic stress plan so the cases are tracked in CI.

#[test]
fn solstudio_stress_plan_is_present() {
    let total = ${stressTests.length};
    assert!(total >= ${stressTests.length});
}

${caseTests || "/* No deterministic stress cases were generated. */"}
`;
}

function renderLiteSvmHarness(stressTests: AuditStressTestCase[]): string {
  return `// Generated by SolStudio audit.
// Add litesvm as a dev-dependency to upgrade these cases into SVM execution tests.

#[test]
fn solstudio_litesvm_stress_plan_is_present() {
    let cases = ${stressTests.length};
    assert!(cases >= ${stressTests.length});
}
`;
}

function renderMolluskHarness(stressTests: AuditStressTestCase[]): string {
  return `// Generated by SolStudio audit.
// Add mollusk-svm as a dev-dependency to upgrade these cases into processor tests.

#[test]
fn solstudio_mollusk_stress_plan_is_present() {
    let cases = ${stressTests.length};
    assert!(cases >= ${stressTests.length});
}
`;
}

function renderReadme(
  framework: AuditTestFramework,
  files: GeneratedAuditTestFile[],
  report: AuditReport,
): string {
  const command =
    framework === "anchor"
      ? "anchor test --skip-local-validator"
      : "cargo test";
  return `# SolStudio Generated Audit Tests

Generated ${report.stressTests.length} deterministic stress case(s).

## Files

${files.map((file) => `- \`${file.path}\``).join("\n")}

## Run

\`\`\`bash
${command}
\`\`\`

The generated harness tracks every SolStudio stress case in CI. Use the JSON file
as the machine-readable source when adding framework-specific LiteSVM or Mollusk
execution fixtures.
`;
}

function normalizeProgramName(value: string): string {
  return value.replace(/[^a-zA-Z0-9_]/g, "_") || "solstudio_program";
}

function rustIdent(value: string): string {
  const ident = value
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return /^[a-z_]/.test(ident) ? ident : `case_${ident}`;
}
