// apps/web/src/server/compile-worker/docker-runner.ts
// Spawns an isolated Docker container to compile Anchor/Pinocchio/Quasar programs.
//
// SERVER ONLY.

import { spawn } from "child_process";
import { mkdir, writeFile, readFile, rm } from "fs/promises";
import { join } from "path";
import { tmpdir } from "os";
import { randomBytes } from "crypto";
import type { ProgramIR } from "@solflow/ir";
import { generateCode } from "@solflow/codegen";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface DockerBuildInput {
  ir: ProgramIR;
  framework: "ANCHOR" | "PINOCCHIO" | "QUASAR";
  irHash: string;
  options: {
    release: boolean;
    verifiable: boolean;
    targetNetwork: "devnet" | "mainnet" | "localnet";
  };
}

export interface DockerBuildResult {
  success: boolean;
  logs: string[];
  errors: string[];
  warnings: string[];
  workDir: string;
  duration: number;
  binaryPath: string | null;
  binarySize: number | null;
  idlJson: string | null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Write generated source files to a temp directory and return its path. */
async function createTempProject(
  ir: ProgramIR,
  framework: "ANCHOR" | "PINOCCHIO" | "QUASAR",
): Promise<string> {
  const dir = join(tmpdir(), `solflow-${randomBytes(8).toString("hex")}`);
  await mkdir(dir, { recursive: true });

  const generatedFramework =
    framework === "ANCHOR" ? "anchor" : framework === "QUASAR" ? "quasar" : "pinocchio";
  const generated = generateCode(ir, generatedFramework);

  for (const file of generated.files) {
    const fullPath = join(dir, file.path);
    const fileDir = fullPath.substring(0, fullPath.lastIndexOf("/"));
    await mkdir(fileDir, { recursive: true });
    await writeFile(fullPath, file.content, "utf8");
  }

  return dir;
}

/** Get the build command for each framework. */
function getBuildCommand(framework: "ANCHOR" | "PINOCCHIO" | "QUASAR"): string {
  switch (framework) {
    case "ANCHOR":
      // Anchor: use `anchor build` which handles cargo-build-sbf + IDL generation
      return "cd /home/builder/project/programs/* && anchor build && anchor idl parse --file src/lib.rs --o /home/builder/project/idl.json 2>/dev/null || true";
    case "QUASAR":
      // Quasar: standard cargo build-sbf (quasar-lang is just a crate dependency)
      return "cd /home/builder/project/programs/* && cargo build-sbf --release";
    case "PINOCCHIO":
      // Pinocchio: standard cargo build-sbf
      return "cd /home/builder/project/programs/* && cargo build-sbf --release";
    default:
      return "cargo build-sbf --release";
  }
}

/** Parse rustc/anchor error lines from log output. */
function parseErrors(logs: string[]): { errors: string[]; warnings: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];

  for (const line of logs) {
    if (/^error(\[E\d+\])?:/.test(line)) errors.push(line.trim());
    else if (/^warning(\[.*\])?:/.test(line)) warnings.push(line.trim());
  }

  return { errors, warnings };
}

/** Try to find the compiled .so binary in the build directory. */
async function findBinary(workDir: string): Promise<{ path: string; size: number } | null> {
  const { readdir, stat } = await import("fs/promises");
  const { extname } = await import("path");

  async function searchDir(dir: string): Promise<{ path: string; size: number } | null> {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return null;
    }

    for (const entry of entries) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        const found = await searchDir(fullPath);
        if (found) return found;
      } else if (extname(entry.name) === ".so") {
        const s = await stat(fullPath);
        return { path: fullPath, size: s.size };
      }
    }
    return null;
  }

  return searchDir(workDir);
}

/** Try to read the IDL file generated by Anchor. */
async function readIdl(workDir: string): Promise<string | null> {
  try {
    const idlPath = join(workDir, "idl.json");
    return await readFile(idlPath, "utf8");
  } catch {
    return null;
  }
}

// ─── Main runner ──────────────────────────────────────────────────────────────

/**
 * Run the compiler Docker container and stream logs via callback.
 * Supports Anchor, Pinocchio, and Quasar frameworks.
 */
export async function runDockerBuild(
  input: DockerBuildInput,
  onLog: (line: string, level: "info" | "warn" | "error") => void,
): Promise<DockerBuildResult> {
  const startedAt = Date.now();
  const logs: string[] = [];

  const workDir = await createTempProject(input.ir, input.framework);
  onLog(`[docker] Source files written to ${workDir}`, "info");

  // Determine the project subdirectory (programs/<name>/)
  const programDir = input.ir.program.name;
  const buildCmd = getBuildCommand(input.framework);

  onLog(`[docker] Framework: ${input.framework}, Build: ${buildCmd}`, "info");

  // Docker run arguments
  const dockerArgs = [
    "run",
    "--rm",
    "--memory=2g",
    "--cpus=2",
    "--network=none",
    "-v",
    `${workDir}:/home/builder/project`,
    "solflow-compiler:latest",
    "/bin/sh",
    "-c",
    buildCmd,
  ];

  return new Promise<DockerBuildResult>((resolve, reject) => {
    const proc = spawn("docker", dockerArgs, { cwd: workDir });

    const appendLog = (
      data: Buffer,
      level: "info" | "warn" | "error" = "info",
    ) => {
      const lines = data.toString().split("\n").filter(Boolean);
      for (const line of lines) {
        logs.push(line);
        const lv = /^error/.test(line)
          ? "error"
          : /^warning/.test(line)
            ? "warn"
            : level;
        onLog(line, lv);
      }
    };

    proc.stdout.on("data", (d: Buffer) => appendLog(d, "info"));
    proc.stderr.on("data", (d: Buffer) => appendLog(d, "warn"));

    proc.on("close", async (code) => {
      const duration = Date.now() - startedAt;
      const { errors, warnings } = parseErrors(logs);
      const success = code === 0;

      if (!success) {
        onLog(`[docker] Build failed (exit code ${code})`, "error");
        await rm(workDir, { recursive: true, force: true }).catch((e) => {
          console.warn(`[docker-runner] Failed to clean ${workDir}:`, e instanceof Error ? e.message : e);
        });
        resolve({
          success: false,
          logs,
          errors,
          warnings,
          workDir: "",
          duration,
          binaryPath: null,
          binarySize: null,
          idlJson: null,
        });
      } else {
        onLog("[docker] Build succeeded", "info");

        // Find the compiled binary
        const binary = await findBinary(workDir);
        if (binary) {
          onLog(`[docker] Binary: ${binary.size} bytes`, "info");
        } else {
          onLog("[docker] No .so binary found in output", "warn");
        }

        // Try to read IDL (Anchor only)
        const idlJson = await readIdl(workDir);
        if (idlJson) {
          onLog("[docker] IDL generated", "info");
        }

        resolve({
          success: true,
          logs,
          errors: [],
          warnings,
          workDir,
          duration,
          binaryPath: binary?.path ?? null,
          binarySize: binary?.size ?? null,
          idlJson,
        });
      }
    });

    proc.on("error", async (err) => {
      const duration = Date.now() - startedAt;
      onLog(`[docker] Docker spawn error: ${err.message}`, "error");
      await rm(workDir, { recursive: true, force: true }).catch(() => undefined);
      reject(new Error(`Docker spawn error: ${err.message}`));
    });

    // Timeout: kill the Docker process after 10 minutes to prevent hangs
    const dockerTimeout = setTimeout(() => {
      proc.kill("SIGKILL");
      onLog("[docker] Build timed out after 10 minutes, killing container", "error");
      reject(new Error("Docker build timed out after 10 minutes"));
    }, 10 * 60_000);

    proc.on("close", () => clearTimeout(dockerTimeout));
  });
}
